version: '3'
services:
  client:
    build:
      context: .
      dockerfile: docker/Dockerfile.client
    volumes:
      - ./client:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - db
  
  server:
    build:
      context: .
      dockerfile: docker/Dockerfile.server
    volumes:
      - ./server:/app
      - /app/node_modules
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
      DB_HOST: db

  db:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  
volumes:
  pgdata: